### ISSUE TITLE
Throw or return last response on too many redirects?

### ISSUE THREAD

**Issue by kelunik** [amphp/artax#124]
Discuss, currently we throw, which is stupid in case `max-redirects` is `0`.

**Comment by bwoebi** [comment]
Well, if you set max-redirects=0, you _want_ to explicitly not redirect and getting a response with redirects is intentional.
If any other case, you set max-redirects in order to avoid looping. In which case exceeding max-redirects is unexpected and should throw.

So: throw if max-redirects > 0 and redirects > max-redirects.
