### ISSUE TITLE
Final class Request. Why?

### ISSUE THREAD

**Issue by demyan112rv** [amphp/artax#159]
https://github.com/amphp/artax/blob/84ba8e2014a81e399541f3dc3a6352bab09c980c/lib/Request.php#L8

I want to create child class for Request class and add custom method to this class, but `Request` class is `final`. Now i copy paste the same lines many times over.

This is example custom method:
```php
public function withAuthHeader(string $token): self
{
    return $this->withHeader('Authorization', "Bearer {$token}")
}

```
Maybe you can tell me some solution for this case?

**Comment by kelunik** [comment]
We make everything `final`-by-default, because it helps avoiding BC breaks where we add such a method to the class, which breaks people's code extending the class then.

In this case you can just go with the slightly longer form of `$request = $request->withHeader(...)` I guess. Version 4 will introduce a concept of middleware, so you could use a middleware then to add such a header automatically.

**Comment by demyan112rv** [comment]
@kelunik Thank you for your fast answer! I think this isuue can be closed.
