### ISSUE TITLE
Background PHP processes

### ISSUE THREAD

**Issue by b-viguier** [amphp/artax#163]
Hi,
I am testing several (dummy) scenarios with Artax, and I found this strange case: when my script finish, I still have a background php process wasting 100% of my cpu…

```php
<?php

require __DIR__.'/vendor/autoload.php';

Amp\Loop::run(
    function () {
        $httpClient = new \Amp\Artax\DefaultClient();
        $promise = $httpClient->request("http://localhost:8000/ping.php");

        Amp\Loop::delay(0, function () {
            \Amp\Loop::stop();
        });
    }
);
```

Of course, it's insane to finish the loop while some jobs are in progress, but I wonder if Artax (or AMP) really launch some background process silently, because it could be a problem in production environment. Do you have some hints for me about this?
Thanks in advance!

**Comment by kelunik** [comment]
We indeed launch background processes to allow for non-blocking filesystem access. You can avoid separate processes by installing one of the PHP extensions `ext-eio` or `ext-uv`. The underlying bug is https://github.com/amphp/byte-stream/issues/40. I haven't seen reports of `amphp/parallel` workers staying up with a clean shutdown, but they're clearly not always exiting as supposed in case of a unclean shutdown.

I don't have too much time currently, but that'll change in about two weeks. Maybe a fix will be out even before that.

**Comment by b-viguier** [comment]
Ok, so it's not directly related to Artax, but more to https://github.com/amphp/file right?
As a workaround, to prevent **any** use of thread in my application, is it enough to use `\define("AMP_WORKER", "amp-worker");` in my code? I didn't found any other way to *inject* a `BlockingDriver` instance to the framework.

Thank you for your quick reply and your work :+1:

**Comment by kelunik** [comment]
No, the actual fix needs to happen either in `amphp/byte-stream` or `amphp/parallel`. You don't need to define that constant, you can just change the used driver.

```php
Amp\File\filesystem(new Amp\File\BlockingDriver);
```

**Comment by kelunik** [comment]
@b-viguier Are you on macOS?

**Comment by b-viguier** [comment]
Yes, I'm running Php `7.1.12` on OSX El Capitan `10.11.6`

**Comment by kelunik** [comment]
Please retry after updating your dependencies. Unless you use `ext-uv`, it should work now.

**Comment by b-viguier** [comment]
I confirm that all is working like a charm now :+1:

Again, thank you for your support 👏

**Comment by kelunik** [comment]
Thanks for confirming! :+1:
