### ISSUE TITLE
Headers should not be forced to lower case

### ISSUE THREAD

**Issue by Bilge** [amphp/artax#164]
I checked the source and didn't find any indication as to why this is done, but the client should return headers verbatim from the server. This just seems like wasted CPU cycles.

**Comment by kelunik** [comment]
HTTP headers are case insensitive, so we need that normalization step either way. We just don't waste additional CPU cycles to return the verbatim response again, which would require additional data structures.

**Comment by Bilge** [comment]
Why do you need a normalization step?

**Comment by kelunik** [comment]
Because `getHeader('conTenT-Type')` must return the `Content-Type` header if present.

**Comment by Bilge** [comment]
That just means you need a case-insensitive search, not that you should permanently manipulate the headers and misrepresent the information returned by the server.

**Comment by kelunik** [comment]
Doing such a search is pretty expensive compared to the current method. You propose an O(n) search for each access, while the current method is O(1) per operation, because it's a simple hash table lookup. As I said, there could be an additional lookup for the original casing, but for most applications there's not much use for that.

Lower case headers aren't a misconfiguration, it's perfectly fine. With HTTP/2 all headers are always lower case anyway.
